apiVersion: v1
kind: ServiceAccount
metadata:
  name: rails-app-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::477655840830:role/rails_app-eks-cluster-cluster-20250716063055353400000003
